source 'http://rubygems.org'

ruby '1.9.3'

gem 'redis-caches', :git=>"git://github.com/CalculatedContent/redis-caches.git"
gem 'sourcify', :git=>"git://github.com/CalculatedContent/sourcify.git" 
gem 'qless', :git=>"git://github.com/CalculatedContent/qless.git"

# helper scripts
gem 'sinatra'
gem 'headless'
gem 'selenium-webdriver'
gem 'whenever'
gem 'fog'

gem 'pry'

gem 'qless-threaded_worker', :path => "/Users/rahulbapna/sites/qless-threaded_worker"

gemspec
