source 'http://rubygems.org'

ruby '1.9.3'

gem 'redis-caches', :git=>"git://github.com/CalculatedContent/redis-caches.git"
gem 'sourcify', :git=>"git://github.com/CalculatedContent/sourcify.git" 
gem 'qless', :git=>"git://github.com/jrbapna/qless.git", :branch=>'master'

# helper scripts
gem 'sinatra'
gem 'headless'
gem 'selenium-webdriver'
gem 'whenever'
gem 'fog'

gem 'pry'

#gem 'qless-threaded_worker', :git => "git://github.com/jrbapna/qless-threaded_worker.git", :branch=>'master'

gem 'pusher'

gem 'vegas'

gem 'qmore'

gemspec
